update data_dir permissions
sous-chefs/etcd pull request #112
Opened 2020-12-02 08:30 UTC by v-andrius

# Description
update data_dir mode to 0700 to fix warning on v3.4.14:
>etcd[709]: check file permission: directory "/hostname.etcd" exist, but the permission is "drwxr-xr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2020-12-02 17:09 UTC, ramereth requested changes
We can safely ignore the failure on Fedora as it looks like upstream hasn't released packages for F33 yet.

2020-12-02 17:09 UTC, ramereth commented on CHANGELOG.md
> +- Update permisions to 0700 on data_dir
```suggestion
- Update permissions to 0700 on data_dir
```

2020-12-03 18:30 UTC, ramereth approved these changes
Since this may impact users, I'm going to release this as a minor release.

2020-12-03 18:30 UTC, merged

2020-12-03 18:30 UTC, kitchen-porter commented
Released as: [6.2.0](https://github.com/sous-chefs/etcd/releases/tag/6.2.0)