add configuration flag listen-metrics-urls
sous-chefs/etcd pull request #113
Opened 2020-12-04 08:02 UTC by v-andrius

# Description

- Add configuration flag [listen-metrics-urls](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--listen-metrics-urls) 
etcd v3.4.14
Certificate is required to access endpoint `/metrics` and `/health` endpoints throught `https`
`--listen-metrics-urls` configuration flag can be used to configure access metrics without authentication

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2020-12-04 17:10 UTC, ramereth requested changes
Can you please also update the documentation to reflect these new parameters? Thanks!

2020-12-04 17:10 UTC, ramereth commented on CHANGELOG.md
> +- Add configuration flag [listen-metrics-urls](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--listen-metrics-urls)
This should be moved above under the `## Unreleased` header. Also, please don't change the release date in this release as it will automatically be changed through our release process.

2020-12-07 19:38 UTC, ramereth approved these changes

2020-12-07 19:39 UTC, merged

2020-12-07 19:39 UTC, kitchen-porter commented
Released as: [6.3.0](https://github.com/sous-chefs/etcd/releases/tag/6.3.0)